export const USER_SCENARIO_PAYLOADS = {
  demo_low: {
    person_age: 29,
    person_income: 92000,
    person_home_ownership: "MORTGAGE",
    person_emp_length: 6,
    loan_intent: "HOMEIMPROVEMENT",
    loan_grade: "A",
    loan_amnt: 12000,
    loan_int_rate: 8.4,
    loan_percent_income: 0.13,
    cb_person_default_on_file: "N",
    cb_person_cred_hist_length: 8,
  },
  demo_moderate: {
    person_age: 34,
    person_income: 64000,
    person_home_ownership: "RENT",
    person_emp_length: 4,
    loan_intent: "PERSONAL",
    loan_grade: "C",
    loan_amnt: 19000,
    loan_int_rate: 14.0,
    loan_percent_income: 0.3,
    cb_person_default_on_file: "N",
    cb_person_cred_hist_length: 6,
  },
  demo_high: {
    person_age: 24,
    person_income: 38000,
    person_home_ownership: "RENT",
    person_emp_length: 1,
    loan_intent: "MEDICAL",
    loan_grade: "F",
    loan_amnt: 18000,
    loan_int_rate: 21.5,
    loan_percent_income: 0.47,
    cb_person_default_on_file: "Y",
    cb_person_cred_hist_length: 2,
  },
};
